version: '3'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - 27018:27017
    volumes:
      - 'mongo:/data/db'

  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api:
    depends_on:
      - mongo
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    restart: always
    ports:
      - 5001:5001
    expose:
      - 5001
    volumes:
      - '/app/node_modules'
      - './api:/app'
    environment:
      SECRET: a211221684
      PORT: 5001
      MONGO_DB: 'mongodb://mongo/app'

  client:
    depends_on:
      - api
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - '/app/node_modules'
      - './client:/app'
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7.28
    container_name: dev_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80


  # jsreport:
  #   container_name: jsreport
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./api-reports
  #   ports:
  #     - 5488:5488
  #   volumes:
  #     - '/app/node_modules'
  #     - './api-reports:/app'
  #   restart: always

volumes:
  mongo:
  mysql_data:
