version: '3'

volumes:
  mongo: # Database
  mongoc: # Mongo config

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - 27017:27017
    restart: unless-stopped
    # volumes:
    #   - mongo:/data/db
    #   - mongoc:/data/configdb

  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api:
    depends_on:
      - mongo
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3005:3005'
    expose:
      # Opens port 3306 on the container
      - '3005'
    volumes:
      - '/app/node_modules'
      - './api:/app'
    environment:
      SECRET: a211221684
      PORT: 3005
      MONGO_DB: 'mongodb://mongo/app'

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3000:3000'
    expose:
      # Opens port 3306 on the container
      - '3000'
    volumes:
      - '/app/node_modules'
      - './client:/app'
    stdin_open: true
    tty: true
