version: '3'

services:
  jsreport:
    container_name: jsreport
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 5488:5488
    restart: always
    environment:
      SECRET: a211221684
      USERNAME: ghost
      PASSWORD: ghost
      PORT: 5488
