# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Copy only package.json and yarn.lock for cache
COPY package*.json ./
# Install some depenendencies
RUN npm install

# Copies everything over to Docker environment
COPY . .

# Finally runs the application
CMD [ "npm", "start" ]