# Specify a base image
FROM node:alpine

WORKDIR '/app'

# Copy only package.json and yarn.lock for cache
COPY package.json yarn.lock ./

# Install api project dependencies
RUN yarn --pure-lockfile

# Copies everything over to Docker environment
COPY . .

# Finally runs the application
CMD [ "yarn", "start" ]